import { Fragment } from "react";
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const Layout = (props: any) => {
    return(
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* <MainNavigation />
                <NavInfo /> */}
                {props.children}
            </main>
        </Fragment>
    )
}

export default Layout;